# Generated by Django 5.1.3 on 2024-11-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('id_proveedores', models.IntegerField()),
                ('id_sucursal', models.IntegerField()),
                ('TipoProducto', models.CharField(max_length=100)),
                ('Cantidad', models.CharField(max_length=100)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('Sucursal', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('NumTelefono', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
