# Generated by Django 5.1.3 on 2024-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('id_Productos', models.IntegerField()),
                ('id_Clientes', models.IntegerField()),
                ('Cantidad', models.CharField(max_length=100)),
                ('Hora_venta', models.CharField(max_length=4)),
                ('Sucursal', models.CharField(max_length=100)),
                ('Marcas', models.CharField(max_length=100)),
                ('FormaPago', models.CharField(default='Efectivo', max_length=50)),
            ],
        ),
    ]
