# Generated by Django 5.1.3 on 2024-11-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedores', models.IntegerField()),
                ('Producto', models.CharField(max_length=100)),
                ('Cantidad', models.CharField(max_length=100)),
                ('Sucursal', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('Horario', models.IntegerField()),
                ('FechaVenta', models.IntegerField()),
            ],
        ),
    ]
