# Generated by Django 5.1.3 on 2024-11-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='Horario',
            new_name='Hora',
        ),
    ]
