# Generated by Django 5.1.3 on 2024-11-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursales',
            name='creditos',
        ),
    ]
