# Generated by Django 5.1.3 on 2024-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.IntegerField()),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('numtelefono', models.IntegerField()),
                ('CURP', models.CharField(max_length=100)),
                ('RFC', models.CharField(max_length=100)),
                ('Edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
            ],
        ),
    ]
