# Generated by Django 5.1.3 on 2024-11-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('NombreCompleto', models.CharField(max_length=100)),
                ('Edad', models.IntegerField(default=0)),
                ('NumeroTelefono', models.IntegerField(default=0)),
                ('Correo', models.CharField(max_length=100)),
                ('Domicilio', models.CharField(max_length=100)),
                ('FormaPago', models.CharField(default='Efectivo', max_length=50)),
            ],
        ),
    ]
